//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dice_and_Combat_Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dice_and_Combat_Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap backgroundBlur {
            get {
                object obj = ResourceManager.GetObject("backgroundBlur", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Goblin
        ///Description: An ugly green thing
        ///Friendly: False
        ///HP: 5
        ///AB: 1
        ///AC: 15
        ///Damage: 6
        ///XP: 5
        ///Strength: 0
        ///Constitution: 1
        ///Dexterity: 1
        ///Intelligence: 0
        ///Wisdom: -1
        ///Charisma: -2
        ///
        ///Name: Orc
        ///Description: A large beastly thing
        ///Friendly: False
        ///HP: 5
        ///AB: 1
        ///AC: 13
        ///Damage: 6
        ///XP: 10
        ///Strength: 3
        ///Constitution: 1
        ///Dexterity: 0
        ///Intelligence: -1
        ///Wisdom: -2
        ///Charisma: -2
        ///
        ///Name: Zombie
        ///Description: Something that should be dead
        ///Friendly: False
        ///HP: 16
        ///AB: 2
        ///AC: 11
        ///Damage: 6
        ///XP: 15
        ///Streng [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string creatures {
            get {
                return ResourceManager.GetString("creatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID: 1
        ///Name: Short Sword
        ///Description: A short slashing utility
        ///Durability: 10
        ///Value: 15
        ///DamageBonus: 5
        ///
        ///ID: 1
        ///Name: Long Sword 
        ///Description: A long slashing utility
        ///Durability: 12
        ///Value: 15
        ///DamageBonus: 6
        ///
        ///ID: 1
        ///Name: Bastard Sword
        ///Description: Bastard child of blades
        ///Durability: 6
        ///Value 40
        ///DamageBonus: 10
        ///
        ///ID: 1
        ///Name: Reinforced Spork
        ///Description: Eat with might
        ///Durability: 666
        ///Value: 420
        ///DamageBonus: 0
        ///
        ///ID: 1
        ///Name: Anti Dragon Tech
        ///Description: You&apos;re doomed without it
        ///Durabi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Hall of Sophia
        ///NumCreatures: 3
        ///NumItems: 3
        ///
        ///Name: Hall of The Pleroma
        ///NumCreatures: 4
        ///NumItems: 5
        ///
        ///Name: Hall of The Monad
        ///NumCreatures: 5
        ///NumItems: 5
        ///
        ///Name: Hall of the Void
        ///NumCreatures: 2
        ///NumItems: 1
        ///
        ///Name: Hall of The Ogdoad
        ///NumCreatures: 6
        ///NumItems: 5.
        /// </summary>
        internal static string rooms {
            get {
                return ResourceManager.GetString("rooms", resourceCulture);
            }
        }
    }
}
